### PR TITLE
Fix requirements for installing via quelpa

### PR DESCRIPTION
**Pull request by averrin**

### CODE REVIEW

**Comment by sid-kurias** [comment]
thanks. I will take a look at quelpa.  I am in the process of merging some of the changes you send wrt to dart-mode. Remember company-dart depends on my fork of dart-mode. So I will give both a different version number and see about using them on quelpa.

**Comment by averrin** [comment]
I created config layer for spacemacs (https://github.com/syl20bnr/spacemacs/pull/8406) and spent whole day trying make it work. Results in this pr=) When you update both repos i will change links in layer to yours.
1. company-mode -> company is necessary
2. remove dart-mode version - not needed, i forgot revert it from pr

**Comment by sid-kurias** [comment]
made the changes.

**Comment by averrin** [comment]
Nice! I updated my config-layer.

**Comment by averrin** [comment]
@sid-kurias cant find dart-mode/issues page =(
Are you going on implement some settings for dart-mode? E.g. line length for dartfmt.

**Pull request closed without merging**
